---
title: "table"
author: "Antoniuk Davyd"
date: "2024-01-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(writexl)
adres <- c("id_adresu", "ulica", "numer_domu", "numer_mieszkania", "kod_pocztowy", "miasto")
klient <- c("id_klienta", "imie", "nazwisko", "PESEL", "login", "haslo", "id_adresu", "nr_telefonu", "ostatnie_logowanie")
mechanik <- c("id_mechanika", "imie", "nazwisko", "PESEL", "login", "haslo", "data_zatrudnienia", "wynagrodzenie", "id_adresu", "nr_telefonu", "ostatnie_logowanie")
samochod <- c("marka", "model", "nr_rejestracyjny", "nr_VIN", "przebieg", "id_klienta")
wizyta <- c("id_wizyty", "data", "status", "id_klienta", "id_samochodu", "przebieg_w_momencie_wizyty", "opis", "czesci", "cena", "czas_pracownikow", "id_mechanika")
sprzet <- c("nazwa_sprzetu", "status", "opis", "id_wizyty", "data_przegladu")
czesci <- c("id", "nazwa", "cena_w_hurtowni", "id_wizyty")
wykonuje <- c("id_wizyty","id_mechanika")

max_length <- max(length(adres), length(klient), length(mechanik), length(samochod), length(wizyta), length(sprzet), length(czesci),length(wykonuje))

adres <- c(adres, rep("", max_length - length(adres)))
klient <- c(klient, rep("", max_length - length(klient)))
mechanik <- c(mechanik, rep("", max_length - length(mechanik)))
samochod <- c(samochod, rep("", max_length - length(samochod)))
wizyta <- c(wizyta, rep("", max_length - length(wizyta)))
sprzet <- c(sprzet, rep("", max_length - length(sprzet)))
czesci <- c(czesci, rep("", max_length - length(czesci)))
wykonuje <- c(wykonuje, rep("", max_length - length(wykonuje)))

df <- data.frame(Adres = adres, Klient = klient, Mechanik = mechanik, Samochod = samochod, Wizyta = wizyta, Sprzet = sprzet, Czesci = czesci,Wykonuje=wykonuje, row.names = NULL)
write_xlsx(df,"table.xlsx")
```

```{r}
library(writexl)
adres <- c(1, 'ul. Doświadczalna', '5', '10', '20-217', 'Lublin')
klient <- c(1, 'Jan', 'Kowalski', '12345678901', 'jan.kowalski', 'haslo123', 1, '123456789')
mechanik <- c(1, 'Adam', 'Nowak', '98765432101', 'adam.nowak', 'haslo456', '2022-10-02', 5000.00, 1, '987654321')
samochod <- c('Toyota', 'Corolla', 'LU902AH', '12345678901234567', 250000, 1)
wizyta <- c(1, '2024-01-16', 'Zaplanowana', 1, 'Przegląd ogólny', 'Żarówki, filtry', 350.00, 3, 1)
sprzet <- c('Komputer diagnostyczny', 'Sprawny', 'Sprzęt do diagnozy silników', 1, '2024-01-16')
czesci <- c(1, 'Filtr oleju', 20.00, 1)
wykonuje <- c(1, 1)

max_length <- max(length(adres), length(klient), length(mechanik), length(samochod), length(wizyta), length(sprzet), length(czesci),length(wykonuje))

adres <- c(adres, rep("", max_length - length(adres)))
klient <- c(klient, rep("", max_length - length(klient)))
mechanik <- c(mechanik, rep("", max_length - length(mechanik)))
samochod <- c(samochod, rep("", max_length - length(samochod)))
wizyta <- c(wizyta, rep("", max_length - length(wizyta)))
sprzet <- c(sprzet, rep("", max_length - length(sprzet)))
czesci <- c(czesci, rep("", max_length - length(czesci)))
wykonuje <- c(wykonuje, rep("", max_length - length(wykonuje)))

df <- data.frame(Adres = adres, Klient = klient, Mechanik = mechanik, Samochod = samochod, Wizyta = wizyta, Sprzet = sprzet, Czesci = czesci,Wykonuje=wykonuje, row.names = NULL)
df
write_xlsx(df,"table_example.xlsx")
```

